main_chat_id = 0
timezone = "Asia/Bishkek"

[logging]
level = "INFO"

[telegram_bot]
token = ""

[server_api]
base_url = ""

[redis]
host = ""
port = 0
db = 0

[sentry]
is_enabled = false
dsn = ""
traces_sample_rate = 1.0  # 100% of traces to be sent to Sentry

[cloudinary]
cloud_name = ""
api_key = ""
api_secret = ""
